/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './stock-card.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/view_container';
import * as import9 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import10 from '@angular/common/src/pipes/i18n_plural_pipe';
import * as import11 from '@angular/common/src/pipes/number_pipe';
import * as import12 from '@angular/common/src/pipes/date_pipe';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/common/src/localization';
import * as import15 from '@angular/core/src/i18n/tokens';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import19 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/common/src/directives/ng_class';
export class Wrapper_StockCardComponent {
  /*private*/ _eventHandler:Function;
  context:import0.StockCardComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  subscription0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.StockCardComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_stockType(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.stockType = currValue;
      this._expr_0 = currValue;
    }
  }
  check_stockState(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.stockState = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.update.subscribe(_eventHandler.bind(view,'update'))); }
  }
}
var renderType_StockCardComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_StockCardComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.StockCardComponent>;
  _StockCardComponent_0_3:Wrapper_StockCardComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_StockCardComponent_Host0,renderType_StockCardComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'stock-card',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_StockCardComponent0(this.viewUtils,this,0,this._el_0);
    this._StockCardComponent_0_3 = new Wrapper_StockCardComponent();
    this.compView_0.create(this._StockCardComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._StockCardComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.StockCardComponent) && (0 === requestNodeIndex))) { return this._StockCardComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._StockCardComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._StockCardComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const StockCardComponentNgFactory:import7.ComponentFactory<import0.StockCardComponent> = new import7.ComponentFactory<import0.StockCardComponent>('stock-card',View_StockCardComponent_Host0,import0.StockCardComponent);
const styles_StockCardComponent:any[] = ([] as any[]);
var renderType_StockCardComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_StockCardComponent,{});
export class View_StockCardComponent0 extends import2.AppView<import0.StockCardComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import8.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import9.Wrapper_NgIf;
  _text_1:any;
  _pipe_i18nPlural_0:import10.I18nPluralPipe;
  _pipe_number_1:import11.DecimalPipe;
  _pipe_date_2:import12.DatePipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_StockCardComponent0,renderType_StockCardComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import8.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import13.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import9.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._pipe_i18nPlural_0 = new import10.I18nPluralPipe(this.parentView.injectorGet(import14.NgLocalization,this.parentIndex));
    this._pipe_number_1 = new import11.DecimalPipe(this.parentView.injectorGet(import15.LOCALE_ID,this.parentIndex));
    this._pipe_date_2 = new import12.DatePipe(this.parentView.injectorGet(import15.LOCALE_ID,this.parentIndex));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._anchor_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import16.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.stock;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 0)) { return new View_StockCardComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}
class View_StockCardComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import8.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import9.Wrapper_NgIf;
  _text_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import8.ViewContainer;
  _TemplateRef_5_5:any;
  _NgIf_5_6:import9.Wrapper_NgIf;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_StockCardComponent1,renderType_StockCardComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import8.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import13.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import9.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n\n  ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_5 = new import8.ViewContainer(5,0,this,this._anchor_5);
    this._TemplateRef_5_5 = new import13.TemplateRef_(this,5,this._anchor_5);
    this._NgIf_5_6 = new import9.Wrapper_NgIf(this._vc_5.vcRef,this._TemplateRef_5_5);
    this._text_6 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import13.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import16.NgIf) && (5 === requestNodeIndex))) { return this._NgIf_5_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.stockState;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_5_0_0:boolean = !this.parentView.context.stockState;
    this._NgIf_5_6.check_ngIf(currVal_5_0_0,throwOnChange,false);
    this._NgIf_5_6.ngDoCheck(this,this._anchor_5,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_5.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 2)) { return new View_StockCardComponent2(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 5)) { return new View_StockCardComponent3(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    return (null as any);
  }
}
class View_StockCardComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _NgClass_47_3:import17.Wrapper_NgClass;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_79:any;
  _pipe_i18nPlural_0_0:any;
  /*private*/ _expr_81:any;
  _pipe_number_1_0:any;
  /*private*/ _expr_83:any;
  _pipe_i18nPlural_0_1:any;
  _map_85:any;
  /*private*/ _expr_86:any;
  _pipe_number_1_1:any;
  _pipe_number_1_2:any;
  /*private*/ _expr_89:any;
  _pipe_date_2_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_StockCardComponent2,renderType_StockCardComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_78 = import1.UNINITIALIZED;
    this._expr_79 = import1.UNINITIALIZED;
    this._expr_81 = import1.UNINITIALIZED;
    this._expr_83 = import1.UNINITIALIZED;
    this._map_85 = import3.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        up: p0,
        down: p1
      }
      ;
    });
    this._expr_86 = import1.UNINITIALIZED;
    this._expr_89 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row stock-card-symbol'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'section',new import3.InlineArray2(2,'class','col-xs '),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_7 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_5,'header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_13 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_5,'article',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','stock-label'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'stock symbol',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._text_25 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._text_26 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._text_27 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n\n      ',(null as any));
    this._text_32 = this.renderer.createText(this._el_30,'\n      ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_30,'div',new import3.InlineArray2(2,'class',' col-xs stock-value'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_33,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'',(null as any));
    this._text_40 = this.renderer.createText(this._el_33,'\n      ',(null as any));
    this._text_41 = this.renderer.createText(this._el_30,'\n\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._text_43 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','stock-trend row middle-xs'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n      ',(null as any));
    this._text_46 = this.renderer.createText(this._el_44,'\n      ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_44,'li',new import3.InlineArray2(2,'class','col-xs-6 col-md-5 col-sm-5 stock-trend-value up'),(null as any));
    this._NgClass_47_3 = new import17.Wrapper_NgClass(this.parentView.parentView.injectorGet(import18.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.KeyValueDiffers,this.parentView.parentIndex),new import20.ElementRef(this._el_47),this.renderer);
    this._text_48 = this.renderer.createText(this._el_47,'\n        ',(null as any));
    this._text_49 = this.renderer.createText(this._el_47,'\n        ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_47,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'',(null as any));
    this._text_52 = this.renderer.createText(this._el_47,'\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_47,'\n        ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_47,'div',new import3.InlineArray2(2,'class','stock-label'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n          ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'trend',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._text_59 = this.renderer.createText(this._el_47,'\n      ',(null as any));
    this._text_60 = this.renderer.createText(this._el_44,'\n\n      ',(null as any));
    this._text_61 = this.renderer.createText(this._el_44,'\n      ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_44,'li',new import3.InlineArray2(2,'class','col-xs-6 col-md-6 col-sm-5 stock-trend-value'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'\n        ',(null as any));
    this._text_64 = this.renderer.createText(this._el_62,'\n        ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_62,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'',(null as any));
    this._text_67 = this.renderer.createText(this._el_62,'\n        ',(null as any));
    this._text_68 = this.renderer.createText(this._el_62,'\n        ',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_62,'div',new import3.InlineArray2(2,'class','stock-label'),(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'\n          ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_69,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'updated',(null as any));
    this._text_73 = this.renderer.createText(this._el_69,'\n        ',(null as any));
    this._text_74 = this.renderer.createText(this._el_62,'\n      ',(null as any));
    this._text_75 = this.renderer.createText(this._el_44,'\n    ',(null as any));
    this._text_76 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._pipe_i18nPlural_0_0 = import3.pureProxy2((<View_StockCardComponent0>this.parentView.parentView)._pipe_i18nPlural_0.transform.bind((<View_StockCardComponent0>this.parentView.parentView)._pipe_i18nPlural_0));
    this._pipe_number_1_0 = import3.pureProxy2((<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1.transform.bind((<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1));
    this._pipe_i18nPlural_0_1 = import3.pureProxy2((<View_StockCardComponent0>this.parentView.parentView)._pipe_i18nPlural_0.transform.bind((<View_StockCardComponent0>this.parentView.parentView)._pipe_i18nPlural_0));
    this._pipe_number_1_1 = import3.pureProxy2((<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1.transform.bind((<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1));
    this._pipe_number_1_2 = import3.pureProxy2((<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1.transform.bind((<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1));
    this._pipe_date_2_0 = import3.pureProxy2((<View_StockCardComponent0>this.parentView.parentView)._pipe_date_2.transform.bind((<View_StockCardComponent0>this.parentView.parentView)._pipe_date_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.NgClass) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgClass_47_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_47_0_0:any = 'col-xs-6 col-md-5 col-sm-5 stock-trend-value up';
    this._NgClass_47_3.check_klass(currVal_47_0_0,throwOnChange,false);
    const currVal_47_0_1:any = this._map_85(this.parentView.parentView.context.stock.positive,!this.parentView.parentView.context.stock.positive);
    this._NgClass_47_3.check_ngClass(currVal_47_0_1,throwOnChange,false);
    this._NgClass_47_3.ngDoCheck(this,this._el_47,throwOnChange);
    const currVal_78:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.stockType,'');
    if (import3.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this.renderer.setText(this._text_11,currVal_78);
      this._expr_78 = currVal_78;
    }
    valUnwrapper.reset();
    const currVal_79:any = import3.inlineInterpolate(1,' ',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nPlural_0_0,(<View_StockCardComponent0>this.parentView.parentView)._pipe_i18nPlural_0.transform)(this.parentView.parentView.context.stockType,this.parentView.parentView.context.stockMappingSYMBOLS)),' ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_79,currVal_79))) {
      this.renderer.setText(this._text_18,currVal_79);
      this._expr_79 = currVal_79;
    }
    valUnwrapper.reset();
    const currVal_81:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_number_1_0,(<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1.transform)(this.parentView.parentView.context.stock.value,'2.3-3')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_81,currVal_81))) {
      this.renderer.setText(this._text_36,currVal_81);
      this._expr_81 = currVal_81;
    }
    valUnwrapper.reset();
    const currVal_83:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nPlural_0_1,(<View_StockCardComponent0>this.parentView.parentView)._pipe_i18nPlural_0.transform)(this.parentView.parentView.context.stockType,this.parentView.parentView.context.stockMappingCURRENCY)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_83,currVal_83))) {
      this.renderer.setText(this._text_39,currVal_83);
      this._expr_83 = currVal_83;
    }
    valUnwrapper.reset();
    const currVal_86:any = import3.inlineInterpolate(2,'\n          ',(this.parentView.parentView.context.stock.trendSymbol + valUnwrapper.unwrap(import3.castByValue(this._pipe_number_1_1,(<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1.transform)(this.parentView.parentView.context.stock.change,'1.3-3'))),'\n          (',((this.parentView.parentView.context.stock.trendSymbol + valUnwrapper.unwrap(import3.castByValue(this._pipe_number_1_2,(<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1.transform)(this.parentView.parentView.context.stock.percentChange,'1.2-2'))) + '%'),')\n        ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_86,currVal_86))) {
      this.renderer.setText(this._text_51,currVal_86);
      this._expr_86 = currVal_86;
    }
    valUnwrapper.reset();
    const currVal_89:any = import3.inlineInterpolate(1,'\n          ',valUnwrapper.unwrap(import3.castByValue(this._pipe_date_2_0,(<View_StockCardComponent0>this.parentView.parentView)._pipe_date_2.transform)(this.parentView.parentView.context.stock.updateDate,'MMM dd, HH:mm:ss')),'\n        ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_89,currVal_89))) {
      this.renderer.setText(this._text_66,currVal_89);
      this._expr_89 = currVal_89;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_StockCardComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _NgClass_15_3:import17.Wrapper_NgClass;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  _pipe_number_1_3:any;
  _map_23:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_StockCardComponent3,renderType_StockCardComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_20 = import1.UNINITIALIZED;
    this._expr_21 = import1.UNINITIALIZED;
    this._map_23 = import3.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'icon-chevron-up': p0,
        'icon-chevron-down': p1
      }
      ;
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'section',new import3.InlineArray2(2,'class','row middle-xs stock-card-symbol'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'header',new import3.InlineArray2(2,'class','col-xs-4'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'article',new import3.InlineArray2(2,'class','col-xs-8'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n      ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','stock-value'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'i',new import3.InlineArray2(2,'class','icon'),(null as any));
    this._NgClass_15_3 = new import17.Wrapper_NgClass(this.parentView.parentView.injectorGet(import18.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.KeyValueDiffers,this.parentView.parentIndex),new import20.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_6));
    this._pipe_number_1_3 = import3.pureProxy2((<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1.transform.bind((<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.NgClass) && (15 === requestNodeIndex))) { return this._NgClass_15_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_15_0_0:any = 'icon';
    this._NgClass_15_3.check_klass(currVal_15_0_0,throwOnChange,false);
    const currVal_15_0_1:any = this._map_23(this.parentView.parentView.context.stock.positive,!this.parentView.parentView.context.stock.positive);
    this._NgClass_15_3.check_ngClass(currVal_15_0_1,throwOnChange,false);
    this._NgClass_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_20:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.stockType,'');
    if (import3.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_7,currVal_20);
      this._expr_20 = currVal_20;
    }
    valUnwrapper.reset();
    const currVal_21:any = import3.inlineInterpolate(1,'\n        ',valUnwrapper.unwrap(import3.castByValue(this._pipe_number_1_3,(<View_StockCardComponent0>this.parentView.parentView)._pipe_number_1.transform)(this.parentView.parentView.context.stock.value,'2.3-3')),'\n        ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_21,currVal_21))) {
      this.renderer.setText(this._text_14,currVal_21);
      this._expr_21 = currVal_21;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.activate()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}