/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './weather.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/view_container';
import * as import9 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import10 from '@angular/common/src/pipes/number_pipe';
import * as import11 from '@angular/common/src/pipes/date_pipe';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/core/src/i18n/tokens';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/common/src/directives/ng_class';
export class Wrapper_WeatherComponent {
  /*private*/ _eventHandler:Function;
  context:import0.WeatherComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.WeatherComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_WeatherComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_WeatherComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.WeatherComponent>;
  _WeatherComponent_0_3:Wrapper_WeatherComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WeatherComponent_Host0,renderType_WeatherComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'weather',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_WeatherComponent0(this.viewUtils,this,0,this._el_0);
    this._WeatherComponent_0_3 = new Wrapper_WeatherComponent();
    this.compView_0.create(this._WeatherComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._WeatherComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.WeatherComponent) && (0 === requestNodeIndex))) { return this._WeatherComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._WeatherComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const WeatherComponentNgFactory:import7.ComponentFactory<import0.WeatherComponent> = new import7.ComponentFactory<import0.WeatherComponent>('weather',View_WeatherComponent_Host0,import0.WeatherComponent);
const styles_WeatherComponent:any[] = ([] as any[]);
var renderType_WeatherComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_WeatherComponent,{});
export class View_WeatherComponent0 extends import1.AppView<import0.WeatherComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import8.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import9.Wrapper_NgIf;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _pipe_number_0:import10.DecimalPipe;
  _pipe_date_1:import11.DatePipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WeatherComponent0,renderType_WeatherComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-3 col-md-offset-9 col-xs-8 col-xs-offset-4 col-lg-2 col-lg-offset-8'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_4 = new import8.ViewContainer(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import12.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import9.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._pipe_number_0 = new import10.DecimalPipe(this.parentView.injectorGet(import13.LOCALE_ID,this.parentIndex));
    this._pipe_date_1 = new import11.DatePipe(this.parentView.injectorGet(import13.LOCALE_ID,this.parentIndex));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import14.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:any = this.context.weather;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 4)) { return new View_WeatherComponent1(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}
class View_WeatherComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _NgClass_13_3:import15.Wrapper_NgClass;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  /*private*/ _expr_27:any;
  _pipe_number_0_0:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  _pipe_date_1_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_WeatherComponent1,renderType_WeatherComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_27 = import6.UNINITIALIZED;
    this._expr_29 = import6.UNINITIALIZED;
    this._expr_30 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row middle-xs'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-xs-4'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h3',new import3.InlineArray2(2,'class','temperature'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_6 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-xs-8'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'h6',new import3.InlineArray2(2,'class','description'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'span',new import3.InlineArray2(2,'class','icon'),(null as any));
    this._NgClass_13_3 = new import15.Wrapper_NgClass(this.parentView.parentView.injectorGet(import16.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import17.KeyValueDiffers,this.parentView.parentIndex),new import18.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_11,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_9,'h4',new import3.InlineArray2(2,'class','city'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,' Moscow, Russia ',(null as any));
    this._text_21 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_9,'h4',new import3.InlineArray2(2,'class','date'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._pipe_number_0_0 = import3.pureProxy2((<View_WeatherComponent0>this.parentView)._pipe_number_0.transform.bind((<View_WeatherComponent0>this.parentView)._pipe_number_0));
    this._pipe_date_1_0 = import3.pureProxy2((<View_WeatherComponent0>this.parentView)._pipe_date_1.transform.bind((<View_WeatherComponent0>this.parentView)._pipe_date_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.NgClass) && (13 === requestNodeIndex))) { return this._NgClass_13_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    const currVal_13_0_0:any = 'icon';
    this._NgClass_13_3.check_klass(currVal_13_0_0,throwOnChange,false);
    const currVal_13_0_1:any = import3.inlineInterpolate(1,'icon-',this.parentView.context.weather.icon,'');
    this._NgClass_13_3.check_ngClass(currVal_13_0_1,throwOnChange,false);
    this._NgClass_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    valUnwrapper.reset();
    const currVal_27:any = import3.inlineInterpolate(1,'\n          ',(this.parentView.context.weather.symbol + valUnwrapper.unwrap(import3.castByValue(this._pipe_number_0_0,(<View_WeatherComponent0>this.parentView)._pipe_number_0.transform)(this.parentView.context.weather.value,'1.0-0'))),'\n        ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_27,currVal_27))) {
      this.renderer.setText(this._text_6,currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_29:any = import3.inlineInterpolate(1,'',this.parentView.context.weather.description,'');
    if (import3.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setText(this._text_16,currVal_29);
      this._expr_29 = currVal_29;
    }
    valUnwrapper.reset();
    const currVal_30:any = import3.inlineInterpolate(1,' ',valUnwrapper.unwrap(import3.castByValue(this._pipe_date_1_0,(<View_WeatherComponent0>this.parentView)._pipe_date_1.transform)(this.parentView.context.weather.updateDate,'EEE dd, HH:mm:ss')),' ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_30,currVal_30))) {
      this.renderer.setText(this._text_23,currVal_30);
      this._expr_30 = currVal_30;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}