/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './source.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/view_container';
import * as import9 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import10 from '@angular/common/src/pipes/lowercase_pipe';
import * as import11 from '@angular/common/src/pipes/uppercase_pipe';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import14 from '@angular/common/src/directives/ng_for';
import * as import15 from '../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import16 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/common/src/directives/ng_class';
import * as import19 from '@angular/core/src/security';
export class Wrapper_SourceComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SourceComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.SourceComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_SourceComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_SourceComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SourceComponent>;
  _SourceComponent_0_3:Wrapper_SourceComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SourceComponent_Host0,renderType_SourceComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'sources',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SourceComponent0(this.viewUtils,this,0,this._el_0);
    this._SourceComponent_0_3 = new Wrapper_SourceComponent();
    this.compView_0.create(this._SourceComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._SourceComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SourceComponent) && (0 === requestNodeIndex))) { return this._SourceComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SourceComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SourceComponentNgFactory:import7.ComponentFactory<import0.SourceComponent> = new import7.ComponentFactory<import0.SourceComponent>('sources',View_SourceComponent_Host0,import0.SourceComponent);
const styles_SourceComponent:any[] = ([] as any[]);
var renderType_SourceComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_SourceComponent,{});
export class View_SourceComponent0 extends import1.AppView<import0.SourceComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _vc_7:import8.ViewContainer;
  _TemplateRef_7_5:any;
  _NgFor_7_6:import9.Wrapper_NgFor;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _pipe_lowercase_0:import10.LowerCasePipe;
  _pipe_uppercase_1:import11.UpperCasePipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SourceComponent0,renderType_SourceComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','row center-xs'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-6 col-sm-8 col-xs-12 col-lg-5'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row start-xs'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._text_6 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_7 = new import8.ViewContainer(7,4,this,this._anchor_7);
    this._TemplateRef_7_5 = new import12.TemplateRef_(this,7,this._anchor_7);
    this._NgFor_7_6 = new import9.Wrapper_NgFor(this._vc_7.vcRef,this._TemplateRef_7_5,this.parentView.injectorGet(import13.IterableDiffers,this.parentIndex),this.ref);
    this._text_8 = this.renderer.createText(this._el_4,' ',(null as any));
    this._text_9 = this.renderer.createText(this._el_4,'\n\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_2,' ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._pipe_lowercase_0 = new import10.LowerCasePipe();
    this._pipe_uppercase_1 = new import11.UpperCasePipe();
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import14.NgFor) && (7 === requestNodeIndex))) { return this._NgFor_7_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7_0_0:any = this.context.sources;
    this._NgFor_7_6.check_ngForOf(currVal_7_0_0,throwOnChange,false);
    this._NgFor_7_6.ngDoCheck(this,this._anchor_7,throwOnChange);
    this._vc_7.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_7.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 7)) { return new View_SourceComponent1(this.viewUtils,this,7,this._anchor_7,this._vc_7); }
    return (null as any);
  }
}
class View_SourceComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _NgClass_9_3:import15.Wrapper_NgClass;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  /*private*/ _expr_30:any;
  _pipe_lowercase_0_0:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  _pipe_uppercase_1_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_SourceComponent1,renderType_SourceComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_30 = import6.UNINITIALIZED;
    this._expr_32 = import6.UNINITIALIZED;
    this._expr_33 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-sm-4 col-md-4 col-xs-4'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row middle-xs source'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-4 col-sm-4 hide-xs'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'h4',new import3.InlineArray2(2,'class','symbol'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'i',new import3.InlineArray2(2,'class','icon'),(null as any));
    this._NgClass_9_3 = new import15.Wrapper_NgClass(this.parentView.parentView.injectorGet(import13.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import16.KeyValueDiffers,this.parentView.parentIndex),new import17.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-8'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_14,'h6',new import3.InlineArray2(2,'class','title'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_14,'h6',new import3.InlineArray2(2,'class','link'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n              ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'a',new import3.InlineArray2(2,'target','_blank'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_14,'\n          ',(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._pipe_lowercase_0_0 = import3.pureProxy1((<View_SourceComponent0>this.parentView)._pipe_lowercase_0.transform.bind((<View_SourceComponent0>this.parentView)._pipe_lowercase_0));
    this._pipe_uppercase_1_0 = import3.pureProxy1((<View_SourceComponent0>this.parentView)._pipe_uppercase_1.transform.bind((<View_SourceComponent0>this.parentView)._pipe_uppercase_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.NgClass) && (9 === requestNodeIndex))) { return this._NgClass_9_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    const currVal_9_0_0:any = 'icon';
    this._NgClass_9_3.check_klass(currVal_9_0_0,throwOnChange,false);
    const currVal_9_0_1:any = import3.inlineInterpolate(1,'',this.context.$implicit.icon,'');
    this._NgClass_9_3.check_ngClass(currVal_9_0_1,throwOnChange,false);
    this._NgClass_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    valUnwrapper.reset();
    const currVal_30:any = import3.inlineInterpolate(1,'\n              ',valUnwrapper.unwrap(import3.castByValue(this._pipe_lowercase_0_0,(<View_SourceComponent0>this.parentView)._pipe_lowercase_0.transform)(this.context.$implicit.title)),'\n            ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_30,currVal_30))) {
      this.renderer.setText(this._text_18,currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_32:any = this.context.$implicit.link;
    if (import3.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementAttribute(this._el_23,'href',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.URL,currVal_32) == null)? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.URL,currVal_32).toString()));
      this._expr_32 = currVal_32;
    }
    valUnwrapper.reset();
    const currVal_33:any = import3.inlineInterpolate(1,' ',valUnwrapper.unwrap(import3.castByValue(this._pipe_uppercase_1_0,(<View_SourceComponent0>this.parentView)._pipe_uppercase_1.transform)(this.context.$implicit.source)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_33,currVal_33))) {
      this.renderer.setText(this._text_24,currVal_33);
      this._expr_33 = currVal_33;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}