/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './components/weather/weather.component';
import * as import9 from './components/weather/weather.component.ngfactory';
import * as import10 from './components/stock/stock.component';
import * as import11 from './components/stock/stock.component.ngfactory';
import * as import12 from './components/source/source.component';
import * as import13 from './components/source/source.component.ngfactory';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-entry',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('app-entry',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import8.WeatherComponent>;
  _WeatherComponent_4_3:import9.Wrapper_WeatherComponent;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  compView_10:import1.AppView<import10.StockComponent>;
  _StockComponent_10_3:import11.Wrapper_StockComponent;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  compView_17:import1.AppView<import12.SourceComponent>;
  _SourceComponent_17_3:import13.Wrapper_SourceComponent;
  _text_18:any;
  _text_19:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'header',new import3.InlineArray2(2,'class','row top-xs'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._text_3 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_1,'weather',new import3.InlineArray2(2,'class','col-xs'),(null as any));
    this.compView_4 = new import9.View_WeatherComponent0(this.viewUtils,this,4,this._el_4);
    this._WeatherComponent_4_3 = new import9.Wrapper_WeatherComponent();
    this.compView_4.create(this._WeatherComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,parentRenderNode,'main',new import3.InlineArray2(2,'class','row middle-xs center-xs'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n\n  ',(null as any));
    this._text_9 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_7,'stock-list',new import3.InlineArray2(2,'class','col-xs'),(null as any));
    this.compView_10 = new import11.View_StockComponent0(this.viewUtils,this,10,this._el_10);
    this._StockComponent_10_3 = new import11.Wrapper_StockComponent();
    this.compView_10.create(this._StockComponent_10_3.context);
    this._text_11 = this.renderer.createText(this._el_7,'\n\n',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,parentRenderNode,'footer',new import3.InlineArray2(2,'class','row bottom-xs'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n\n  ',(null as any));
    this._text_16 = this.renderer.createText(this._el_14,'\n  ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_14,'sources',new import3.InlineArray2(2,'class','col-xs'),(null as any));
    this.compView_17 = new import13.View_SourceComponent0(this.viewUtils,this,17,this._el_17);
    this._SourceComponent_17_3 = new import13.Wrapper_SourceComponent();
    this.compView_17.create(this._SourceComponent_17_3.context);
    this._text_18 = this.renderer.createText(this._el_14,'\n\n',(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.WeatherComponent) && (4 === requestNodeIndex))) { return this._WeatherComponent_4_3.context; }
    if (((token === import10.StockComponent) && (10 === requestNodeIndex))) { return this._StockComponent_10_3.context; }
    if (((token === import12.SourceComponent) && (17 === requestNodeIndex))) { return this._SourceComponent_17_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._WeatherComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._StockComponent_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    this._SourceComponent_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
    this.compView_10.detectChanges(throwOnChange);
    this.compView_17.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_4.destroy();
    this.compView_10.destroy();
    this.compView_17.destroy();
  }
}